name: hello-world-deployment

releases:
- name: hello-world
  version: latest

stemcells:
- alias: default
  os: ubuntu-jammy
  version: latest

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

instance_groups:
- name: server
  azs: ["null"]
  instances: 1
  vm_type: default
  stemcell: default
  networks:
  - name: network
  jobs:
  - name: hello-world
    release: hello-world
    templates:
    - name: hello-world
      release: hello-world
